#Sets the amout of (digital) currency a player should receive on joining the first time.
#Set to 0 to disable.
default-amount: 50

#Auto balance
#Delay in sec
#A player is counted as AFK if they have not moved between the current and last attempt to give them money
autobalance:
  enabled: true
  delay: 300
  amount: 5
  ignore-afk: false

#Data Storage
#Why mysql is disabled,sqlite will be used
mysql:
  enabled: false
  url: 127.0.0.1
  port: 3306
  user: minecraft
  password: password
  database: minecraft
  prefix: sc_

#Items for the withdrawal and deposit command
#These must be sorted by value (ascending)
#Item(type) and CustomModelData are used for identification for /deposit
#Set CustomModelData if you want to prevent crafted items
#This will not prevent any duplication glitches, which you risk by having and Item Based economy
#To prevent duplication set the "simple-currency.deposit" and "simple-currency.withdraw" permissions false for everyone
#Set CustomModelData to null if you want to allow crafted items
items:
  - value: 1
    item: "GOLD_NUGGET"
    name: "&r&6&lGold Nugget"
    lore:
      - "&5{0} coin"
    customModelData: null
  - value: 5
    item: "GOLD_INGOT"
    name: "&r&6&lGold Ingot"
    lore:
      - "&5{0} coins"
    customModelData: null
  - value: 10
    item: "GOLD_BLOCK"
    name: "&r&6&lGold Block"
    lore:
      - "&5{0} coins"
    customModelData: null

messages:
  balance: "[$] &aYour balance: &e{0} coins"
  balance-others: "[$] &a{0}s balance: &e{1} coins"
  set: "[$] &aSuccessfully changed {0} balance."
  payed: "[$] &aYou successfully gave {0} &e{1} coins."
  received: "[$] &a{0} gave you &e{1} coins."
  bank:
    title: "[$] &6&l{0}s coin account"
    current-balance: "&7Current balance: &e{0} coins"
    deposit: "» &aDeposit Coins"
    withdraw: "» &aWithdraw Coins"
    pay: "» &aPay someone"
  withdrawal:
    title: "[$] &6&lYou received:"
    items: "» &a{0} {1}"
  deposit:
    success: "[$] &aYou deposited {0} coins into your account"
    invalid: "[$] &cYou do not have a currency item in your hand."
  errors:
    console: "&cThis command is only available to players."
    no-self: "[$] &cYou can't pay yourself."
    no-negatives: "[$] &cPlease use a positive amount."
    not-enough-money: "[$] &cYou do not have enough coins. You need {0} coins but only have {1}."
    not-enough-space: "[$] &cYou do not have enough space in you inventory."
    invalid-player: "[$] &cPlease provide a player on the server."
    invalid-player-offline: "[$] &cThis player is not know on this server."
    int-required: "[$] &cPlease provide an integer for argument {0}"
    missing-arguments: "[$] &cPlease add all arguments"
    missing-permissions: "[$] &cYou are not permitted to do that."